CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "AspNetRoles" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text,
    CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
);

CREATE TABLE "AspNetUsers" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
);

CREATE TABLE "AspNetRoleClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" integer NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" integer NOT NULL,
    CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserRoles" (
    "UserId" integer NOT NULL,
    "RoleId" integer NOT NULL,
    CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserTokens" (
    "UserId" integer NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text,
    CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Resumes" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "Title" character varying(128) NOT NULL,
    "OwnerName" character varying(128) NOT NULL,
    "Location" text,
    "Email" text NOT NULL,
    "NormalizedEmail" text NOT NULL,
    "PhoneNumber" text NOT NULL,
    "Keywords" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_Resumes" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Resumes_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AcademicDegrees" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Highlights" text,
    "Level" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "ResumeId" integer NOT NULL,
    "Name" character varying(128) NOT NULL,
    "Description" character varying(256) NOT NULL,
    "InstitutionName" character varying(128) NOT NULL,
    "Location" character varying(64),
    "IsRemote" boolean NOT NULL,
    "StartDate" timestamp with time zone NOT NULL,
    "EndDate" timestamp with time zone,
    "StillEngaged" boolean NOT NULL,
    CONSTRAINT "PK_AcademicDegrees" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AcademicDegrees_Resumes_ResumeId" FOREIGN KEY ("ResumeId") REFERENCES "Resumes" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Certificates" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CredentialId" text,
    "CredentialUrl" text,
    "Type" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "ResumeId" integer NOT NULL,
    "Name" character varying(128) NOT NULL,
    "Description" character varying(256) NOT NULL,
    "InstitutionName" character varying(128) NOT NULL,
    "Location" character varying(64),
    "IsRemote" boolean NOT NULL,
    "StartDate" timestamp with time zone NOT NULL,
    "EndDate" timestamp with time zone,
    "StillEngaged" boolean NOT NULL,
    CONSTRAINT "PK_Certificates" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Certificates_Resumes_ResumeId" FOREIGN KEY ("ResumeId") REFERENCES "Resumes" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Experiences" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Highlights" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "ResumeId" integer NOT NULL,
    "Name" character varying(128) NOT NULL,
    "Description" character varying(256) NOT NULL,
    "InstitutionName" character varying(128) NOT NULL,
    "Location" character varying(64),
    "IsRemote" boolean NOT NULL,
    "StartDate" timestamp with time zone NOT NULL,
    "EndDate" timestamp with time zone,
    "StillEngaged" boolean NOT NULL,
    CONSTRAINT "PK_Experiences" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Experiences_Resumes_ResumeId" FOREIGN KEY ("ResumeId") REFERENCES "Resumes" ("Id") ON DELETE CASCADE
);

CREATE TABLE "VolunteerExperiences" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "ResumeId" integer NOT NULL,
    "Name" character varying(128) NOT NULL,
    "Description" character varying(256) NOT NULL,
    "InstitutionName" character varying(128) NOT NULL,
    "Location" character varying(64),
    "IsRemote" boolean NOT NULL,
    "StartDate" timestamp with time zone NOT NULL,
    "EndDate" timestamp with time zone,
    "StillEngaged" boolean NOT NULL,
    CONSTRAINT "PK_VolunteerExperiences" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_VolunteerExperiences_Resumes_ResumeId" FOREIGN KEY ("ResumeId") REFERENCES "Resumes" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_AcademicDegrees_ResumeId" ON "AcademicDegrees" ("ResumeId");

CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");

CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");

CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");

CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");

CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");

CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");

CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");

CREATE INDEX "IX_Certificates_ResumeId" ON "Certificates" ("ResumeId");

CREATE INDEX "IX_Experiences_ResumeId" ON "Experiences" ("ResumeId");

CREATE INDEX "IX_Resumes_UserId" ON "Resumes" ("UserId");

CREATE INDEX "IX_VolunteerExperiences_ResumeId" ON "VolunteerExperiences" ("ResumeId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251130173226_Schema', '9.0.11');

COMMIT;


