name: resumi

services:
  backend:
    image: ${DOCKER_REGISTRY-}resumi-backend:development
    container_name: resumi_backend
    build:
      context: .
      dockerfile: Dockerfile.debug
      labels:
        - org.osderivados=resumi
        - environment=development
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - JWT_SIGNING_KEY=${JWT_SIGNING_KEY}
      - JWT_ISSUER=${JWT_ISSUER}
      - JWT_AUDIENCE=${JWT_AUDIENCE}
      - ADMIN_USER=${ADMIN_USER}
      - ALLOWED_ORIGIN=${ALLOWED_ORIGIN}
      - "ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=resumi;Username=resumi;Password=postgres"
    ports:
      - "8081:8081" # HTTPS
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - resumi-network

  db:
    image: docker.io/library/postgres:18-alpine
    container_name: resumi_db
    environment:
      - POSTGRES_DB=resumi
      - POSTGRES_USER=resumi
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/18/docker
      - ./backend/Resumi/Infra/Database/Migrations/Schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U resumi -d resumi" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - resumi-network

volumes:
  db_data:

networks:
  resumi-network:
